// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CasterInputReducer from "../caster_input_reducer";
import FireReducer from "../fire_reducer";
import JoinReducer from "../join_reducer";
import ResetMatchReducer from "../reset_match_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartRoundReducer from "../start_round_reducer";
import SubmitInputReducer from "../submit_input_reducer";

export type CasterInputParams = __Infer<typeof CasterInputReducer>;
export type FireParams = __Infer<typeof FireReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type ResetMatchParams = __Infer<typeof ResetMatchReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;
export type SubmitInputParams = __Infer<typeof SubmitInputReducer>;

