// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchState,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  round: __t.u32(),
  scoreA: __t.u32().name("score_a"),
  scoreB: __t.u32().name("score_b"),
  roundTimerMs: __t.u64().name("round_timer_ms"),
  get state() {
    return MatchState;
  },
});
