// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchState,
  GoldenVoteState,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  round: __t.u32(),
  scoreA: __t.u32().name("score_a"),
  scoreB: __t.u32().name("score_b"),
  roundTimerMs: __t.u64().name("round_timer_ms"),
  get state() {
    return MatchState;
  },
  roundEndTimestamp: __t.timestamp().name("round_end_timestamp"),
  get goldenVoteState() {
    return GoldenVoteState.name("golden_vote_state");
  },
  goldenVoteEndsAt: __t.i64().name("golden_vote_ends_at"),
  goldenVoteWinnerId: __t.u32().name("golden_vote_winner_id"),
});
