// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  matchRound: __t.u32().name("match_round"),
  winningTeam: __t.u8().name("winning_team"),
  teamAKills: __t.u32().name("team_a_kills"),
  teamBKills: __t.u32().name("team_b_kills"),
  playedAt: __t.timestamp().name("played_at"),
});
