// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
  Vec2,
  AnimState,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  identity: __t.identity(),
  name: __t.string(),
  team: __t.u8(),
  get position() {
    return Vec3;
  },
  get aimVector() {
    return Vec3.name("aim_vector");
  },
  get lean() {
    return Vec2;
  },
  crouch: __t.bool(),
  health: __t.u8(),
  ammo: __t.u8(),
  alive: __t.bool(),
  get animState() {
    return AnimState.name("anim_state");
  },
  kills: __t.u32(),
});
