// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  shooterId: __t.u32().name("shooter_id"),
  get aimVector() {
    return Vec3.name("aim_vector");
  },
  hit: __t.bool(),
  victimId: __t.option(__t.u32()).name("victim_id"),
  damage: __t.u8(),
  firedAt: __t.timestamp().name("fired_at"),
});
