// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Vec3,
  Vec2,
} from "./types";

export default {
  get aim() {
    return Vec3;
  },
  get lean() {
    return Vec2;
  },
  crouch: __t.bool(),
  fire: __t.bool(),
  reload: __t.bool(),
};
