// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AnimState`.
export const AnimState = __t.enum("AnimState", {
  Idle: __t.unit(),
  Walk: __t.unit(),
  StrafeL: __t.unit(),
  StrafeR: __t.unit(),
  WalkBack: __t.unit(),
  Crouch: __t.unit(),
  Fire: __t.unit(),
  Reload: __t.unit(),
  Hit: __t.unit(),
  Death: __t.unit(),
  VictoryArms: __t.unit(),
  GrabbingPistol: __t.unit(),
});
export type AnimState = __Infer<typeof AnimState>;

export const Commentary = __t.object("Commentary", {
  id: __t.u64(),
  get kind() {
    return CommentaryKind;
  },
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Commentary = __Infer<typeof Commentary>;

// The tagged union or sum type for the algebraic type `CommentaryKind`.
export const CommentaryKind = __t.enum("CommentaryKind", {
  Bark: __t.unit(),
  Color: __t.unit(),
});
export type CommentaryKind = __Infer<typeof CommentaryKind>;

export const GameMatch = __t.object("GameMatch", {
  id: __t.u32(),
  round: __t.u32(),
  scoreA: __t.u32(),
  scoreB: __t.u32(),
  roundTimerMs: __t.u64(),
  get state() {
    return MatchState;
  },
  roundEndTimestamp: __t.timestamp(),
});
export type GameMatch = __Infer<typeof GameMatch>;

export const LeaderboardRow = __t.object("LeaderboardRow", {
  id: __t.u64(),
  matchRound: __t.u32(),
  winningTeam: __t.u8(),
  teamAKills: __t.u32(),
  teamBKills: __t.u32(),
  playedAt: __t.timestamp(),
});
export type LeaderboardRow = __Infer<typeof LeaderboardRow>;

// The tagged union or sum type for the algebraic type `MatchState`.
export const MatchState = __t.enum("MatchState", {
  Lobby: __t.unit(),
  Live: __t.unit(),
  RoundEnd: __t.unit(),
  MatchEnd: __t.unit(),
});
export type MatchState = __Infer<typeof MatchState>;

export const Player = __t.object("Player", {
  id: __t.u32(),
  identity: __t.identity(),
  name: __t.string(),
  team: __t.u8(),
  get position() {
    return Vec3;
  },
  get aimVector() {
    return Vec3;
  },
  get lean() {
    return Vec2;
  },
  crouch: __t.bool(),
  health: __t.u8(),
  ammo: __t.u8(),
  alive: __t.bool(),
  get animState() {
    return AnimState;
  },
  kills: __t.u32(),
  deaths: __t.u32(),
  ready: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Shot = __t.object("Shot", {
  id: __t.u64(),
  shooterId: __t.u32(),
  get aimVector() {
    return Vec3;
  },
  hit: __t.bool(),
  victimId: __t.option(__t.u32()),
  damage: __t.u8(),
  killed: __t.bool(),
  firedAt: __t.timestamp(),
});
export type Shot = __Infer<typeof Shot>;

export const Spectator = __t.object("Spectator", {
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type Spectator = __Infer<typeof Spectator>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Vec2 = __t.object("Vec2", {
  x: __t.f32(),
  z: __t.f32(),
});
export type Vec2 = __Infer<typeof Vec2>;

export const Vec3 = __t.object("Vec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type Vec3 = __Infer<typeof Vec3>;

